from random import choice

from cookeyTyperTypes import (
    EffectType,
    FacilityConfig,
    FacilityTypes,
    Parameters,
    UpgradeConfig,
    UpgradeTypes,
    VisualState,
)


def parameters() -> Parameters:
    return {"facility_cost_multiplier_by_amount": 1.15, "tick_rate": 20}


def upgrades() -> dict[UpgradeTypes, UpgradeConfig]:
    return {
        UpgradeTypes.REINFORCED_INDEX_FINGER: {
            "name": "Reinforced index finger",
            "description": "The keyboard gains +1 base CPS.",
            "price": 100,
            "target": FacilityTypes.KEYBOARD,
            "effect_type": EffectType.ADD,
            "value": 1.0,
            "unlock_facility": FacilityTypes.KEYBOARD,
            "unlock_count": 1,
        },
        UpgradeTypes.CARPAL_TUNNEL_PREVENTION: {
            "name": "Carpal tunnel prevention cream",
            "description": "The keyboard gains +1 base CPS.",
            "price": 500,
            "target": FacilityTypes.KEYBOARD,
            "effect_type": EffectType.ADD,
            "value": 1.0,
            "unlock_facility": FacilityTypes.KEYBOARD,
            "unlock_count": 1,
        },
        UpgradeTypes.AMBIDEXTROUS: {
            "name": "Ambidextrous",
            "description": "The keyboard is twice as efficient.",
            "price": 10000,
            "target": FacilityTypes.KEYBOARD,
            "effect_type": EffectType.MULTIPLIER,
            "value": 2.0,
            "unlock_facility": FacilityTypes.KEYBOARD,
            "unlock_count": 10,
        },
        UpgradeTypes.FORWARD_FROM_GRANDMA: {
            "name": "Forwards from grandma",
            "description": "Grandmas gain +1 base CPS.",
            "price": 1000,
            "target": FacilityTypes.GRANDMA,
            "effect_type": EffectType.ADD,
            "value": 1.0,
            "unlock_facility": FacilityTypes.GRANDMA,
            "unlock_count": 1,
        },
        UpgradeTypes.STEEL_PLATED_ROLLING_PINS: {
            "name": "Steel-plated rolling pins",
            "description": "Grandmas are twice as efficient.",
            "price": 5000,
            "target": FacilityTypes.GRANDMA,
            "effect_type": EffectType.MULTIPLIER,
            "value": 2.0,
            "unlock_facility": FacilityTypes.GRANDMA,
            "unlock_count": 5,
        },
        UpgradeTypes.CHEAP_HOES: {
            "name": "Cheap hoes",
            "description": "Farms gain +4 base CPS.",
            "price": 11000,
            "target": FacilityTypes.FARM,
            "effect_type": EffectType.ADD,
            "value": 4.0,
            "unlock_facility": FacilityTypes.FARM,
            "unlock_count": 1,
        },
        UpgradeTypes.FERTILIZER: {
            "name": "Fertilizer",
            "description": "Farms are twice as efficient.",
            "price": 55000,
            "target": FacilityTypes.FARM,
            "effect_type": EffectType.MULTIPLIER,
            "value": 2.0,
            "unlock_facility": FacilityTypes.FARM,
            "unlock_count": 5,
        },
        UpgradeTypes.SUGAR_GAS: {
            "name": "Sugar gas",
            "description": "Mines gain +23 base CPS.",
            "price": 120000,
            "target": FacilityTypes.MINE,
            "effect_type": EffectType.ADD,
            "value": 23.0,
            "unlock_facility": FacilityTypes.MINE,
            "unlock_count": 1,
        },
        UpgradeTypes.MEGADRILL: {
            "name": "Megadrill",
            "description": "Mines are twice as efficient.",
            "price": 600000,
            "target": FacilityTypes.MINE,
            "effect_type": EffectType.MULTIPLIER,
            "value": 2.0,
            "unlock_facility": FacilityTypes.MINE,
            "unlock_count": 5,
        },
    }


def facilities() -> dict[FacilityTypes, FacilityConfig]:
    return {
        FacilityTypes.KEYBOARD: {
            "name": "Keyboard",
            "description": "Autotypes once every 10 seconds.",
            "base_cost": 15,
            "base_cps": 0.1,
            "init_visual": VisualState.COVERED,
        },
        FacilityTypes.GRANDMA: {
            "name": "Grandma",
            "description": "Nice grandma to bake more cookies.",
            "base_cost": 100,
            "base_cps": 1,
            "init_visual": VisualState.COVERED,
        },
        FacilityTypes.FARM: {
            "name": "Farm",
            "description": "Grows cookie plants from cookie seeds.",
            "base_cost": 1100,
            "base_cps": 8,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.MINE: {
            "name": "Mine",
            "description": "Mines our cookie dough and chocolate chips.",
            "base_cost": 12000,
            "base_cps": 47,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.FACTORY: {
            "name": "Factory",
            "description": "Produces large quantities of cookies.",
            "base_cost": 130000,
            "base_cps": 260,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.BANK: {
            "name": "Bank",
            "description": "Generates cookies from interest.",
            "base_cost": 1400000,
            "base_cps": 1400,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.TEMPLE: {
            "name": "Temple",
            "description": "Full of precious, ancient chocolate.",
            "base_cost": 20000000,
            "base_cps": 7800,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.WIZARD_TOWER: {
            "name": "Wizard Tower",
            "description": "Summons cookies with magic spells.",
            "base_cost": 330000000,
            "base_cps": 44000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.SHIPMENT: {
            "name": "Shipment",
            "description": "Brings in fresh cookies from the cookie planet.",
            "base_cost": 5100000000,
            "base_cps": 260000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.ALCHEMY_LAB: {
            "name": "Alchemy Lab",
            "description": "Turns gold into cookies!",
            "base_cost": 75000000000,
            "base_cps": 1600000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.PORTAL: {
            "name": "Portal",
            "description": "Opens a door to the Cookieverse.",
            "base_cost": 1000000000000,
            "base_cps": 10000000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.TIME_MACHINE: {
            "name": "Time Machine",
            "description": "Brings cookies from the past, before they were even eaten.",
            "base_cost": 14000000000000,
            "base_cps": 65000000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.ANTIMATTER_CONDENSER: {
            "name": "Antimatter Condenser",
            "description": "Condenses the antimatter in the universe into cookies.",
            "base_cost": 170000000000000,
            "base_cps": 430000000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.PRISM: {
            "name": "Prism",
            "description": "Converts light itself into cookies.",
            "base_cost": 2100000000000000,
            "base_cps": 2900000000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.CHANCE_MAKER: {
            "name": "Chancemaker",
            "description": "Generates cookies out of thin air through sheer luck.",
            "base_cost": 26000000000000000,
            "base_cps": 21000000000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.FRACTAL_ENGINE: {
            "name": "Fractal Engine",
            "description": "Turns cookies into even more cookies.",
            "base_cost": 310000000000000000,
            "base_cps": 150000000000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.PYTHON_CONSOLE: {
            "name": "Python Console",
            "description": "Creates cookies from the every code this game was written in.",
            "base_cost": 71000000000000000000,
            "base_cps": 1100000000000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.IDLEVERSE: {
            "name": "Idleverse",
            "description": "Hijack other idle universes' production and convert them into cookies!",
            "base_cost": 12000000000000000000000,
            "base_cps": 8300000000000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.CORTEX_BAKER: {
            "name": "Cortex Baker",
            "description": "Artificial brains the size of planets capable of dreaming up cookies.",
            "base_cost": 1900000000000000000000000,
            "base_cps": 64000000000000,
            "init_visual": VisualState.HIDDEN,
        },
        FacilityTypes.YOU: {
            "name": "You",
            "description": "You, alone, are the reason behind all these cookies.",
            "base_cost": 540000000000000000000000000,
            "base_cps": 510000000000000,
            "init_visual": VisualState.HIDDEN,
        },
    }


def random_sentence() -> str:
    random_sentence_database: list[str] = [
        # VCS & Git/Jujutsu
        "jj desc -m 'bugf: fix circular dependency in core'",
        "jj log -r ..@",
        "jj git push",
        "git commit --amend --no-edit",
        "git push origin head --force-with-lease",
        "git rebase -i HEAD~3",
        "jj split",
        "git checkout -b feat/typing-engine",
        "jj abandon",
        "git remote add origin https://github.com/user/repo.git",
        "jj diff --git",
        "git merge --abort",
        "jj undo",
        "git cherry-pick 7f3b2a",
        "git config --global user.name 'nozy'",
        "jj evals",
        "git stash pop",
        "jj branch set main",
        "git rev-parse --short HEAD",
        "jj bookmark set main -r @",
        # Python & uv & Environment
        "uv run main.py",
        "uv add basedpyright --dev",
        "python3 -m venv .venv",
        "pip install -r requirements.txt",
        "uv lock --update",
        "python -c 'import sys; print(sys.path)'",
        "uv self update",
        "export PYTHONPATH=$PYTHONPATH:.",
        "uv run pytest tests/",
        "python -m json.tool config.json",
        "uv init --lib cookeyTyperPy",
        "pip list --outdated",
        "python -O main.py",
        "uv add threading",
        "source .venv/bin/activate",
        "python -m py_compile main.py",
        "uv tree",
        "which python3",
        "uv run ruff check .",
        "python -m http.server 8000",
        # Error Messages
        "ImportError: cannot import name 'CookeyTyper' from 'cookeyTyperCore' (circular import)",
        "NameError: name 'self' is not defined",
        "AttributeError: 'NoneType' object has no attribute 'on_cookie_amount_change'",
        "TypeError: 'int' object is not callable",
        "IndentationError: expected an indented block",
        "SyntaxError: invalid syntax. Maybe you forgot a comma?",
        "IndexError: list index out of range",
        "KeyError: 'target_facility_not_found'",
        "ModuleNotFoundError: No module named 'cookeyTyperHandler'",
        "RuntimeError: dictionary changed size during iteration",
        "RecursionError: maximum recursion depth exceeded",
        "ZeroDivisionError: division by zero (CPS calculation failed)",
        "StopIteration",
        "UnboundLocalError: local variable referenced before assignment",
        "FileNotFoundError: [Errno 2] No such file: 'save_data.json'",
        "PermissionError: [Errno 13] Permission denied",
        "UnicodeDecodeError: 'utf-8' codec can't decode byte",
        "MemoryError: process terminated by OOM killer",
        "AssertionError: Parser failed to enforce target for DETAIL",
        "KeyboardInterrupt",
        # Linux / WSL / Neovim
        "nvim cookeyTyperCore.py",
        "sudo apt update && sudo apt upgrade -y",
        "ls -la /home/user/creation/games/cookeyTyperPy/",
        "rm -rf __pycache__",
        "chmod +x run_game.sh",
        "cat /etc/os-release",
        "grep -r 'CookeyTyper' .",
        "find . -name '*.py' | xargs wc -l",
        "tail -f game.log",
        "ps aux | grep python",
        "kill -9 9999",
        "cd .. && pwd",
        "mkdir -p assets/sounds",
        "curl -fsSL https://astral.sh/uv/install.sh | sh",
        "du -sh .",
        "tar -czvf backup.tar.gz .",
        "ssh-keygen -t ed25519",
        "history | tail -n 20",
        "echo $PATH",
        "top",
        # Logic & Meta & Project
        "while True: self.handler.update()",
        "with self.lock: self.cookies += amount",
        "cost = self.base_cost * (pow(1.15, amount))",
        "return Ok(CommandFacility(operation=Operations.BUY))",
        "if target is None: report_and_die('Parser Bug')",
        "from __future__ import annotations",
        "if TYPE_CHECKING: from cookeyTyper import CookeyTyper",
        "self.stats = CookeyTyperStats(self)",
        "f detail cursor",
        "f buy grandma 10",
        "Total CPS: {total_cps:,.1f}",
        "VisualState.SHOWN",
        "target = command.target",
        "delta = int(abs(raw_total) * 0.5)",
        "Location: Ibaraki-shi, Osaka-fu",
        "Developed in a cozy room in Osaka",
        "def calculate_typing_score(target: str, user_input: str):",
        "if score >= len(target) * 0.9: next_target()",
        "Cookey Typer Engine v0.1.0 started successfully.",
        # --- Neovim & Lua Config ---
        "vim.opt.relativenumber = true",
        "require('telescope').setup({})",
        "vim.keymap.set('n', '<leader>ff', builtin.find_files)",
        "local capabilities = require('cmp_nvim_lsp').default_capabilities()",
        "vim.api.nvim_create_autocmd('TextYankPost', { callback = function() vim.highlight.on_yank() end })",
        "LSP: basedpyright initialized successfully",
        ":checkhealth nvim",
        ":Telescope diagnostics",
        "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'",
        "local lspconfig = require('lspconfig')",
        "vim.diagnostic.goto_next()",
        "vim.fn.setreg('+', 'copied to clipboard')",
        "Error: module 'lazy' not found",
        "require('lualine').setup({ options = { theme = 'tokyonight' } })",
        "vim.o.expandtab = true",
        "vim.o.shiftwidth = 4",
        "vim.o.smartindent = true",
        "Mason: all packages are up to date",
        "LSP: connected to pyright with 0 errors",
        "nvim_buf_set_lines(0, -1, -1, false, { 'new line' })",
        # --- Python Threading & Async ---
        "with self.lock: self.cookies += delta",
        "threading.Thread(target=self.run, daemon=True).start()",
        "event_loop = asyncio.get_event_loop()",
        "future = executor.submit(heavy_task, data)",
        "queue.Queue().put_nowait(command)",
        "time.sleep(0.1) # Avoid 100% CPU usage",
        "stop_event = threading.Event()",
        "if stop_event.is_set(): break",
        "shared_resource = [] # Guard with Lock!",
        "with threading.RLock(): print('Nested lock acquired')",
        "thread_local = threading.local()",
        "async with aiohttp.ClientSession() as session:",
        "await asyncio.gather(*tasks)",
        "multiprocessing.Pool(processes=4)",
        "semaphore = threading.Semaphore(value=5)",
        "main_thread = threading.main_thread()",
        "while not self.queue.empty(): process_queue()",
        "threading.enumerate() # List all active threads",
        "lock.acquire(timeout=5.0)",
        "Condition().notify_all()",
        # --- Jujutsu (jj) & VCS ---
        "jj commit -m 'refactor: split stats into separate module'",
        "jj log -n 5",
        "jj git fetch --all",
        "jj rebase -s @ -d main",
        "jj describe -m 'docs: update README with installation guide'",
        "jj new main",
        "jj bookmark create experimental",
        "jj diff --stat",
        "jj status",
        "jj next",
        "jj prev",
        "jj squash",
        "jj restore --from @-",
        "jj duplicate",
        "jj move --from @ --to main",
        "jj hide -r 'description(\"test\")'",
        "jj show @",
        "jj edit 7f3b",
        "jj obslog",
        "jj branch list",
        # --- uv & Packaging ---
        "uv add requests ruff",
        "uv remove old-package",
        "uv sync --frozen",
        "uv run python main.py",
        "uv tool install black",
        "uv venv .venv --python 3.12",
        "uv generate-shell-completion zsh",
        "uv pip compile requirements.in -o requirements.txt",
        "uv lock --upgrade-package cookeyTyper",
        "uv cache clean",
        "uv run flask run --port 5000",
        "uv init my-project",
        "uv add --optional dev basedpyright",
        "uv export --format setuptools",
        "uv tool list",
        "uv add pydantic",
        "uv run mypy .",
        "uv self-update",
        "uv run python -m unittest discover",
        "uv version",
        # --- Type Hints & Basedpyright ---
        "from typing import Any, Protocol, runtime_checkable",
        "def process(data: list[int | str]) -> None:",
        "type Alias = dict[str, list[float]]",
        "if TYPE_CHECKING: from .core import Engine",
        "assert isinstance(facility, Facility)",
        "cast(str, value).upper()",
        "Final[int] = 100",
        "Annotated[int, 'Cookie Count']",
        "Callable[[int, int], bool]",
        "def get_stats() -> CookeyTyperStats:",
        "TypedDict('User', {'id': int, 'name': str})",
        "NewType('CookieID', int)",
        "Literal['SHOWN', 'HIDDEN', 'COVERED']",
        "Generic[T] # Type variable T",
        "Self # Type of the class itself",
        "Never # Function that never returns",
        "reveal_type(self.engine)",
        "Optional[FacilityTypes] = None",
        "Union[int, float, complex]",
        "list(map(lambda x: x * 2, range(10)))",
        # --- More Errors (The Joy of Debugging) ---
        "ValueError: invalid literal for int() with base 10",
        "ConnectionRefusedError: [Errno 111] Connection refused",
        "OverflowError: cookie count too large for 64-bit integer",
        "TimeoutError: The operation timed out after 30 seconds",
        "NotImplementedError: Method 'update' must be overridden",
        "EOFError: Compressed file ended before the end-of-stream",
        "ImportError: Attempted relative import with no known parent package",
        "TabError: inconsistent use of tabs and spaces in indentation",
        "Warning: Implicit string concatenation in list",
        "UserWarning: Data source is empty, skipping update",
        "RuntimeError: Set changed size during iteration",
        "GeneratorExit",
        "KeyError: 'CookieSource.CLICKS'",
        "LookupError: unknown encoding: utf-32",
        "ProcessLookupError: [Errno 3] No such process",
        "BrokenPipeError: [Errno 32] Broken pipe",
        "FileExistsError: [Errno 17] File exists",
        "InterruptedError: [Errno 4] Interrupted system call",
        "ChildProcessError: [Errno 10] No child processes",
        "ArithmeticError: floating point error",
        # --- Advanced Linux & WSL ---
        "cat /proc/cpuinfo | grep 'model name'",
        "systemctl status docker.service",
        "journalctl -xeu ssh",
        "df -h /mnt/c",
        "wsl --shutdown",
        "wsl --export Ubuntu backup.tar",
        "ip addr show eth0",
        "ping -c 4 google.com",
        "traceroute astral.sh",
        "nslookup localhost",
        "netstat -tulnp",
        "lsof -i :8080",
        "alias ll='ls -alF'",
        "echo $HOME",
        "sed -i 's/foo/bar/g' script.py",
        "awk '{print $1}' log.txt",
        "curl -I https://github.com",
        "wget https://example.com/data.zip",
        "unzip archive.zip -d ./dist",
        "tar -xzvf bundle.tar.gz",
        # --- Game Engine & Logic (cookeyTyperPy) ---
        "facility.visual_state = VisualState.SHOWN",
        "if self.cookies >= facility.cost(): buy()",
        "self.total_baked += self.cps * delta_time",
        "def update_display(self): self.render_table()",
        "cursor.amount += 1; cursor.update_cost()",
        "for f_type, f in self.facilities.items():",
        "match command.operation: case Operations.BUY:",
        "self.engine.stats.save_to_json('save.json')",
        "print(f'Total CPS: {self.engine.get_total_cps():,.2f}')",
        "unlock_manager.register_milestone(1000, 'unlock_grandma')",
        "self.lock.acquire(); self.cookies += 1; self.lock.release()",
        "command = Command(target=FacilityTypes.CURSOR, amount=1)",
        "handler.push_to_queue('f buy cursor 10')",
        "class Facility(Protocol): name: str; cost: Callable[[], float]",
        "delta = self.get_cookie_delta(1, base_amount=10)",
        "if success: self.cookies += delta",
        "self.stats.on_cookie_amount_change(amount, source)",
        "if self.total_baked >= next_tier_cost: reveal()",
        "return {'cps': self.cps, 'amount': self.amount}",
        "CookeyTyper: Engine version 0.1.0-alpha",
        # --- General Programming Jokes & Common Strings ---
        "TODO: refactor this spaghetti code tomorrow",
        "FIXME: this works but I don't know why",
        "// Why is this here? Nobody knows.",
        "print('here')",
        "print('here2')",
        "print('reached this point')",
        "debug = True",
        "if __name__ == '__main__': main()",
        "Hello World!",
        "foo = 'bar'",
        "lorem ipsum dolor sit amet",
        "Quick brown fox jumps over the lazy dog",
        "git commit -m 'initial commit'",
        "git commit -m 'fix typo'",
        "git commit -m 'asdfghjkl'",
        "while(true) { /* infinite loop */ }",
        "exit(0)",
        "return 42",
        "the cake is a lie",
        # --- HTTP & Web Dev ---
        "GET /api/v1/cookies HTTP/1.1",
        "POST /auth/login Content-Type: application/json",
        "HTTP 404: Not Found",
        "HTTP 500: Internal Server Error",
        "HTTP 200: OK",
        "HTTP 403: Forbidden",
        "HTTP 418: I'm a teapot",
        "Set-Cookie: session_id=abc12345; HttpOnly",
        "Authorization: Bearer my_secret_token",
        "Cache-Control: no-cache, no-store, must-revalidate",
        "User-Agent: Mozilla/5.0 (WSL; Ubuntu)",
        "Origin: http://localhost:3000",
        "Access-Control-Allow-Origin: *",
        "JSON.stringify({ cookies: 1000 })",
        "fetch('/buy').then(res => res.json())",
        "console.log('Stats updated')",
        "npm run dev",
        "docker-compose up -d",
        "docker build -t cookey-typer .",
        "kubectl get pods",
        # --- Keyboard / Typing ---
        "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG",
        "typing speed test in progress",
        "accuracy is more important than speed",
        "keep your hands on the home row",
        "spacebar spacebar spacebar",
        "Enter to confirm, Esc to cancel",
        "Tab for autocompletion",
        "Backspace your mistakes",
        "Ctrl+C to terminate",
        "Ctrl+R for reverse search",
        "Alt+Tab to switch windows",
        "Super+Space for launcher",
        "Shift+Insert for paste",
        "Caps Lock is a cruise control for cool",
        # --- Shell Scripting ---
        "#!/bin/bash",
        "for i in {1..10}; do echo $i; done",
        "if [ -f 'file.txt' ]; then echo 'Exists'; fi",
        "read -p 'Enter name: ' user_name",
        "export PATH=$HOME/.local/bin:$PATH",
        "source ~/.bashrc",
        "echo 'Done' > /dev/null",
        "tail -n 50 /var/log/syslog",
        "ps -ef | awk '{print $2}'",
        "grep -v 'pattern' data.csv",
        "ssh user@remote-host",
        "scp local_file remote:/tmp/",
        "rsync -avz ./src/ ./dest/",
        "crontab -e",
        "whoami",
        "hostname -I",
        "uptime",
        "free -m",
        "lsblk",
        # --- Database & SQL ---
        "SELECT * FROM cookies WHERE amount > 100;",
        "UPDATE facilities SET level = level + 1 WHERE id = 1;",
        "INSERT INTO history (event, timestamp) VALUES ('buy', NOW());",
        "DELETE FROM session WHERE expired = true;",
        "CREATE TABLE stats (id SERIAL PRIMARY KEY, cookies BIGINT);",
        "DROP TABLE temp_data;",
        "ALTER TABLE users ADD COLUMN email VARCHAR(255);",
        "SELECT COUNT(*) FROM achievements;",
        "BEGIN TRANSACTION;",
        "COMMIT;",
        "ROLLBACK;",
        "PRAGMA foreign_keys = ON;",
        "EXPLAIN ANALYZE SELECT * FROM large_table;",
        "VACUUM ANALYZE;",
        "REINDEX DATABASE my_game;",
        "SHOW TABLES;",
        "DESCRIBE users;",
        "GRANT ALL PRIVILEGES ON db TO 'user';",
        "REVOKE DELETE ON facilities FROM 'intern';",
        "DATABASE_URL=postgres://user:pass@localhost:5432/db",
        # --- Dev Tools & Misc ---
        "git log --graph --oneline --all",
        "docker ps --format 'table {{.ID}}\t{{.Status}}\t{{.Names}}'",
        "npm audit fix",
        "cargo build --release",
        "rustc main.rs -o main",
        "go run main.go",
        "javac Main.java && java Main",
        "make && sudo make install",
        "gcc -Wall -o program main.c",
        "clang++ -std=c++20 -O3 main.cpp",
        "gdb ./program",
        "valgrind --leak-check=full ./program",
        "strace -e open python3 main.py",
        "htop",
        "tmux attach-session -t dev",
        "screen -r session_name",
        "vi /etc/hosts",
        "nano README.md",
        "cat /dev/urandom | base64 | head -c 32",
        "uuidgen",
        # --- Logic Fragments (Part 2) ---
        "def get_cost(self, n: int) -> int:",
        "self.base_cost * (1.15 ** (self.amount + n))",
        "multiplier = self.global_multipliers.get('cps', 1.0)",
        "for facility in filter(lambda f: f.is_visible, facilities):",
        "if key == Key.Enter: submit_input()",
        "screen.clear(); screen.refresh()",
        "logger.info('User bought 5 cursors')",
        "try: load_save_data() except FileNotFoundError: init_new_game()",
        "stats_data = {'cookies': self.cookies, 'baked': self.total_baked}",
        "json.dump(stats_data, f, indent=4)",
        "self.handler.process_input(raw_str)",
        "if cmd.operation == Operations.LS: display_list()",
        "print('| Name | Owned | Cost |')",
        "formatted_cost = format(int(cost), ',')",
        "return f'{self.name} cost is {formatted_cost}'",
        "while self.running: self.tick()",
        "fps_limiter.wait()",
        "current_time = time.monotonic()",
        "dt = current_time - self.last_update",
        # --- Coding Philosophy & Humor ---
        "Don't repeat yourself (DRY)",
        "Keep it simple, stupid (KISS)",
        "Premature optimization is the root of all evil",
        "It works on my machine",
        "That's not a bug, it's a feature",
        "Legacy code: use with caution",
        "Documentation is like sex: when it's good, it's very good",
        "And when it's bad, it's better than nothing.",
        "First, solve the problem. Then, write the code.",
        "Real programmers count from 0.",
        "A programmer's wife tells him: 'Go to the store and buy a loaf of bread.'",
        "'If they have eggs, buy a dozen.'",
        "He returns with 12 loaves of bread.",
        "'They had eggs,' he explains.",
        "There are 10 types of people in the world:",
        "Those who understand binary, and those who don't.",
        "To understand recursion, you must first understand recursion.",
        "Infinite loop: See 'Infinite loop'",
        "The best code is no code at all.",
        # --- Modern Web & Cloud ---
        "AWS_ACCESS_KEY_ID=AKIA...",
        "gcloud compute instances list",
        "terraform apply -auto-approve",
        "ansible-playbook setup.yml",
        "Serverless functions are just someone else's servers.",
        "GraphQL: query { user { id name } }",
        "WebSocket connected on port 8081",
        "Redis CACHE_HIT for key 'user_1'",
        "Kafka consumer group rebalanced",
        "Docker: container exited with code 137 (OOM)",
        "Kubernetes: ImagePullBackOff",
        "Deployment rollout in progress...",
        "Prometheus metrics scraped",
        "Grafana dashboard updated",
        "CI/CD pipeline: Build Stage Success",
        "GitHub Action: workflow_dispatch",
        "Vercel: Deployment failed due to build error",
        "Netlify: Site is live at unique-url.netlify.app",
        "Firebase: Permission denied in Security Rules",
        "Sentry: New issue 'TypeError' detected in Production",
        # --- Pythonic Idioms ---
        "if __name__ == '__main__':",
        "for item in my_list: process(item)",
        "squares = [x**2 for x in range(10)]",
        "filtered = filter(lambda x: x > 0, data)",
        "with open('file.txt', 'r') as f: content = f.read()",
        "dictionary.get('key', default_value)",
        "all(is_ok for is_ok in checks)",
        "any(has_error for has_error in results)",
        "sum(range(101)) # Sum of first 100 numbers",
        "zip(keys, values)",
        "enumerate(items, start=1)",
        "sorted_list = sorted(data, key=lambda x: x.price)",
        "class MyClass(Base): pass",
        "super().__init__()",
        "@staticmethod",
        "@classmethod",
        "@property",
        "@dataclass",
        "from abc import ABC, abstractmethod",
        "breakpoint() # Python 3.7+ debugger",
        # --- System Admin & Security ---
        "sudo chown -R user:group /var/www",
        "sudo chmod 600 ~/.ssh/id_rsa",
        "ssh-copy-id user@host",
        "iptables -A INPUT -p tcp --dport 22 -j ACCEPT",
        "ufw enable",
        "fail2ban-client status sshd",
        "openssl genrsa -out server.key 2048",
        "nmap -sV -p- localhost",
        "wireshark # Packet capture",
        "dig +short google.com",
        "whois example.com",
        "passwd user_name",
        "visudo",
        "dmesg | tail",
        "lsmod | grep kvm",
        "modprobe vhost_net",
        "echo 1 > /proc/sys/net/ipv4/ip_forward",
        "sysctl -p",
        "dmidecode -s system-serial-number",
        "lscpu",
        # --- Data Science & AI (Bonus) ---
        "import numpy as np",
        "import pandas as pd",
        "df = pd.read_csv('data.csv')",
        "model.fit(X_train, y_train)",
        "prediction = model.predict(X_test)",
        "plt.plot(x, y); plt.show()",
        "loss: 0.045 - accuracy: 0.982",
        "tensor = torch.tensor([1, 2, 3])",
        "optimizer = torch.optim.Adam(model.parameters())",
        "from sklearn.cluster import KMeans",
        "vectorizer = TfidfVectorizer()",
        "hidden_layers = [64, 32, 16]",
        "activation_function = 'relu'",
        "epochs = 10; batch_size = 32",
        "precision, recall, f1_score",
        "confusion_matrix",
        "overfitting is a common problem",
        "regularization factor lambda = 0.01",
        "gradient descent convergence reached",
        "OpenAI API Key: sk-...",
        # --- Final Polish ---
        "self.engine.unlock_manager.check(self.total_baked)",
        "Handler started in daemon thread.",
        "Type 'help' for a list of commands.",
        "Press Ctrl+D to exit.",
        "Happy coding, nozy!",
        "One more cookie...",
        "Wait, I found a bug in line 42.",
        "Refactoring in progress, please wait.",
        "System overload: too many cookies.",
        "Typing speed: 80 WPM. Cookies awarded: 80.",
        "New achievement: Master of Threads",
        "New achievement: Bug Hunter",
        "New achievement: CLI Wizard",
        "Loading Cookey Typer assets...",
        "Initialization complete.",
        "Ready to bake.",
        "Ready to type.",
        "Ready to code.",
        "Ready to commit.",
        "JJ: Done.",
        "Help, I'm trapped in a cookie factory and all I have is this terminal.",
        "The cookies are a lie, but the typos are very, very real.",
        "Error 418: I am a teapot, and I refuse to bake cookies without Earl Grey.",
        "If you type 'rm -rf /', your cookies will turn into crumbs. Please don't.",
        "Basedpyright is actually me, Gemini, disguised as a type checker.",
    ]
    return choice(random_sentence_database)
